{{- include "aether-dataplane.validate" . -}}
{{- if and .Values.herald.enabled .Values.controlPlane.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aether-dataplane.fullname" . }}-control-plane
  labels:
    {{- include "aether-dataplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.controlPlane.token | quote }}
{{- end }}
